/* ========================================================================
   URL UTILITIES
   ========================================================================

   PURPOSE:
   Shared utilities for URL parameter handling and detection.
   Provides common functions used across the application for URL processing.

   EXPORTS:
   - isSharedURL() - Check if current URL contains shared scene parameters

   ======================================================================== */

/**
 * Check if URL contains parameters indicating a shared scene.
 *
 * DETECTION LOGIC — read before changing:
 *
 * Two trigger paths:
 *
 *  1. `?c=<base64>` — the compressed shared-URL format generated by
 *     createShareUrl() / compressUrlParameters() in urlManager.js.
 *     This is the primary path for all URLs generated by the Share button.
 *
 *  2. Uncompressed long-form or short-form camera params — kept for backward
 *     compatibility with URLs generated before base64 compression was added,
 *     and for manually crafted or externally generated URLs.
 *
 *     Recognized params (full name → short code):
 *       model → m    (model URL — the most unambiguous signal)
 *       alpha → a    (camera alpha angle)
 *       beta  → b    (camera beta angle)
 *       radius→ r    (camera radius / zoom)
 *
 * ⚠️  COLLISION RISK — the short params `a`, `b`, `r`, `m` are single letters
 *     and could theoretically match analytics, A/B testing, or UTM query params
 *     added by external tools (e.g. `?a=1` for a variant ID).  If that becomes
 *     a problem in the future, the recommended hardening path is to add a
 *     dedicated sentinel param (`?viewer=1`) to all generated share URLs and
 *     check for that first — keeping the current checks as a fallback for
 *     existing links.  See ROADMAP.md Phase 3.2 for the full trade-off analysis.
 *
 * DO NOT add general-purpose tracking / analytics params here — this list
 * should only contain params that unambiguously signal a viewer share URL.
 *
 * @returns {boolean} True if URL contains shared scene parameters
 */
export function isSharedURL() {
    const urlParams = getCurrentUrlParams();

    // Path 1: compressed URL — generated by Share button via createShareUrl()
    if (urlParams.has('c')) {
        return true;
    }

    // Path 2: uncompressed camera params — backward compatibility for older links
    // and manually crafted URLs.  'model'/'m' is the strongest signal; alpha/beta/
    // radius short codes are included because they appear in legacy uncompressed URLs.
    const sharedParams = ['model', 'm', 'alpha', 'a', 'beta', 'b', 'radius', 'r'];
    return sharedParams.some(param => urlParams.has(param));
}

/**
 * Get current URL parameters as URLSearchParams object
 * @returns {URLSearchParams} Current URL parameters
 */
export function getCurrentUrlParams() {
    return new URLSearchParams(window.location.search);
}

/**
 * Get the base URL without query parameters
 * @returns {string} Base URL without query string
 */
export function getBaseUrl() {
    return window.location.href.split('?')[0];
}

/**
 * Check if a specific parameter exists in the current URL
 * @param {string} paramName - Parameter name to check
 * @returns {boolean} True if parameter exists
 */
export function hasUrlParam(paramName) {
    return getCurrentUrlParams().has(paramName);
}

/**
 * Get a specific parameter value from the current URL
 * @param {string} paramName - Parameter name to get
 * @param {string} [defaultValue] - Default value if parameter doesn't exist
 * @returns {string|null} Parameter value or default
 */
export function getUrlParam(paramName, defaultValue = null) {
    return getCurrentUrlParams().get(paramName) || defaultValue;
}